name: Carrefour Pokémon Scraper

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4

      - name: 🐍 Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: 📦 Install dependencies
        run: |
          pip install --upgrade pip
          pip install playwright requests
          python -m playwright install chromium


      - name: 🚀 Run scraper
        run: python scrapercarrefour.py
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
